### ISSUE TITLE
--debug mode not working due to removal of pyqtWrapperType

### ISSUE THREAD

**Issue by dev-jam** [open-cogsci/OpenSesame#566]
When I try to start opensesame in --debug mode, I get an ImportError: cannot import name pyqtWrapperType.
I am using python-pqt5 5.9 on Debian Buster and PyQt5.QtCore.pyqtWrapperType was removed from this version. 
I found 'pyqtWrapperType' can be replaced by 'type(QObject)'
Applied this change and it works properly now. Patch is attached.

Original error:

Traceback (most recent call last):
  File "/usr/bin/opensesame", line 24, in <module>
    from libqtopensesame import __main__
  File "/usr/lib/python2.7/dist-packages/libqtopensesame/__init__.py", line 27, in <module>
    from libqtopensesame.items import qtplugin
  File "/usr/lib/python2.7/dist-packages/libqtopensesame/items/qtplugin.py", line 24, in <module>
    from libqtopensesame.items import qtitem
  File "/usr/lib/python2.7/dist-packages/libqtopensesame/items/qtitem.py", line 24, in <module>
    from libqtopensesame.widgets.item_view_button import item_view_button
  File "/usr/lib/python2.7/dist-packages/libqtopensesame/widgets/item_view_button.py", line 22, in <module>
    from libqtopensesame.misc.base_subcomponent import base_subcomponent
  File "/usr/lib/python2.7/dist-packages/libqtopensesame/misc/base_subcomponent.py", line 22, in <module>
    from libqtopensesame.misc.base_component import base_component
  File "/usr/lib/python2.7/dist-packages/libqtopensesame/misc/base_component.py", line 30, in <module>
    from libqtopensesame.misc.base_qtobject import base_qtobject
  File "/usr/lib/python2.7/dist-packages/libqtopensesame/misc/base_qtobject.py", line 25, in <module>
    from qtpy.QtCore import pyqtWrapperType
ImportError: cannot import name pyqtWrapperType

[opensesame_wrappertype.patch.txt](https://github.com/smathot/OpenSesame/files/1423630/opensesame_wrappertype.patch.txt)

**Comment by smathot** [comment]
Thanks for this! I don't want to apply this patch, because I'm not sure if it's backwards compatible. So here's another suggestion that doesn't change the old behavior:

~~~ python
	try:
		from qtpy.QtCore import pyqtWrapperType
	except ImportError:
		from qtpy.QtCore import QObject
		pyqtWrapperType = type(QObject)
~~~

Does this fix the issue as well? If so, would you mind submitting this as a pull request?

Cheers!
Sebastiaan

**Comment by dev-jam** [comment]
Took some time to figure out how to do a pull request but it seems to have worked. 
Your suggestions works correctly.

**Comment by smathot** [comment]
Thanks!
