### ISSUE TITLE
Python 3: plugin installation using pip does not work

### ISSUE THREAD

**Issue by PascalKieslich** [open-cogsci/OpenSesame#587]
The installation of plugins from within OpenSesame using pip does not work in the Python 3 version.

When running the following command:
```
import pip
pip.main(['install', 'https://github.com/PascalKieslich/mousetrap-os/archive/master.zip'])
```

I get the following error message:
```
Collecting https://github.com/PascalKieslich/mousetrap-os/archive/master.zip
  Downloading https://github.com/PascalKieslich/mousetrap-os/archive/master.zip
Exception:
Traceback (most recent call last):
  File "C:\Program Files\OpenSesame\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Program Files\OpenSesame\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Program Files\OpenSesame\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Program Files\OpenSesame\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Program Files\OpenSesame\lib\site-packages\pip\req\req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "C:\Program Files\OpenSesame\lib\site-packages\pip\req\req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "C:\Program Files\OpenSesame\lib\site-packages\pip\req\req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "C:\Program Files\OpenSesame\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "C:\Program Files\OpenSesame\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
AttributeError: 'NoneType' object has no attribute 'encoding'
Out[1]: 2
```

This seems to be related to a general issue in pip with Python 3 (e.g., here: https://github.com/pypa/pip/issues/4598) which I think has been fixed in newer versions of pip.

**Comment by smathot** [comment]
Hi Pascal,

Thanks for finding this. I'll close it, because it's not something we can fix from within OpenSesame. As you say, it's a problem with pip itself, which seems to happen in interactive environments such as IPython. (The debug window is just an IPython interpreter.)

Let's keep an eye on it though, and update pip as soon as a release with a fix for this is available. (Right now the fix, if any, is not released yet.)

Cheers!
Sebastiaan
