### ISSUE TITLE
Unable to load saved experiment

### ISSUE THREAD

**Issue by MichlF** [open-cogsci/OpenSesame#690]
I saved an experiment. OS crashed at the end of the saving process and everytime I try to reload the save file now it spits out the following error message and freezes. I can still use the program after a brief moment but the cursor remains the hourglass. Sometimes I also get this message in a pop-up window before:

> Extension get_started misbehaved on event open_recent_1 (see debug window for stack trace)

I don't particularly need this saved file to be restored but I figured if this is a more general problem, it might be worth fixing.

I have the most recent (3.3.0) version of OS installed in a separate anaconda environment and always start the program via the command line. I can share the experiment file if that helps.

Information:

> Operating System: win32
> OpenSesame: 3.3.0
> Python: 3.7.7
> Don't show me this message!
> 
> If you don't want to see bug-report messages in the future, you can disable the bug_report extension under Menu â†’ Tools â†’ Plug-in and extension manager. This does not automagically solve the problem--it only suppresses the report!
> 

Error message:

```
Traceback (most recent call last):
 File "C:\Users\Michl\Anaconda3\envs\opensesame-py3\lib\site-packages\libqtopensesame\qtopensesame.py", line 831, in open_file
  self.experiment.build_item_tree()
 File "C:\Users\Michl\Anaconda3\envs\opensesame-py3\lib\site-packages\libqtopensesame\items\experiment.py", line 145, in build_item_tree
  self.treeitem_general = tree_general_item(self)
 File "C:\Users\Michl\Anaconda3\envs\opensesame-py3\lib\site-packages\libqtopensesame\widgets\tree_general_item.py", line 56, in __init__
  .build_item_tree(self)
 File "C:\Users\Michl\Anaconda3\envs\opensesame-py3\lib\site-packages\libqtopensesame\items\sequence.py", line 147, in build_item_tree
  max_depth=max_depth-1, extra_info=cond)
 File "C:\Users\Michl\Anaconda3\envs\opensesame-py3\lib\site-packages\libqtopensesame\items\loop.py", line 337, in build_item_tree
  max_depth=max_depth-1)
 File "C:\Users\Michl\Anaconda3\envs\opensesame-py3\lib\site-packages\libqtopensesame\items\sequence.py", line 147, in build_item_tree
  max_depth=max_depth-1, extra_info=cond)
 File "C:\Users\Michl\Anaconda3\envs\opensesame-py3\lib\site-packages\libqtopensesame\items\loop.py", line 337, in build_item_tree
  max_depth=max_depth-1)
 File "C:\Users\Michl\Anaconda3\envs\opensesame-py3\lib\site-packages\libqtopensesame\items\sequence.py", line 147, in build_item_tree
  max_depth=max_depth-1, extra_info=cond)
 File "C:\Users\Michl\Anaconda3\envs\opensesame-py3\lib\site-packages\libqtopensesame\items\qtitem.py", line 700, in build_item_tree
  widget = tree_item_item(self, extra_info=extra_info)
 File "C:\Users\Michl\Anaconda3\envs\opensesame-py3\lib\site-packages\libqtopensesame\widgets\tree_item_item.py", line 60, in __init__
  self.setText(1, extra_info)
TypeError: setText(self, int, str): argument 2 has unexpected type 'int'
```

**Comment by smathot** [comment]
> I can share the experiment file if that helps.

Yes, that would be very helpful!

**Comment by MichlF** [comment]
Attached.

[test.zip](https://github.com/smathot/OpenSesame/files/4574584/test.zip)

**Comment by smathot** [comment]
Ok, that's clear. The error is due to the fact that some run-if statements were numbers. That's strange in itself, but it shouldn't crash OpenSesame either ;-)
