### ISSUE TITLE
Inline script crashes

### ISSUE THREAD

**Issue by eort** [open-cogsci/OpenSesame#751]
Hi, 
Just adding an `inline_script` to an experiment leads to an "Oops, I did it again" error (I also sent that bug report). Specifically it says: 

~~~
Traceback (most recent call last):
  File "/home/ede/tools/miniconda3/envs/opensesame3/lib/python3.7/site-packages/libqtopensesame/widgets/tree_overview.py", line 820, in dropEvent
    self.drop_event_item_new(data, e)
  File "/home/ede/tools/miniconda3/envs/opensesame3/lib/python3.7/site-packages/libqtopensesame/widgets/tree_overview.py", line 797, in drop_event_item_new
    item.open_tab()
  File "/home/ede/tools/miniconda3/envs/opensesame3/lib/python3.7/site-packages/libqtopensesame/items/qtitem.py", line 143, in open_tab
    self.tabwidget.add(self.widget(), self.item_icon(), self.name)
  File "/home/ede/tools/miniconda3/envs/opensesame3/lib/python3.7/site-packages/libqtopensesame/items/qtitem.py", line 45, in inner
    self.init_edit_widget()
  File "/home/ede/tools/miniconda3/envs/opensesame3/lib/python3.7/site-packages/libqtopensesame/items/inline_script.py", line 101, in init_edit_widget
    self._pyqode_tab_widget.create_new_document('Prepare', self.ext)
  File "/home/ede/tools/miniconda3/envs/opensesame3/lib/python3.7/site-packages/pyqode/core/widgets/splittable_tab_widget.py", line 1418, in create_new_document
    self.guess_mimetype(name), **kwargs)
  File "/home/ede/tools/miniconda3/envs/opensesame3/lib/python3.7/site-packages/pyqode/core/widgets/splittable_tab_widget.py", line 1379, in _create_code_edit
    **kwargs
  File "/home/ede/tools/miniconda3/envs/opensesame3/share/opensesame_extensions/pyqode_manager/pyqode_extras/widgets/python_code_edit.py", line 70, in __init__
    panels.SearchAndReplacePanel(),
  File "/home/ede/tools/miniconda3/envs/opensesame3/lib/python3.7/site-packages/pyqode/core/panels/search_and_replace.py", line 161, in __init__
    self._init_actions()
  File "/home/ede/tools/miniconda3/envs/opensesame3/lib/python3.7/site-packages/pyqode/core/panels/search_and_replace.py", line 170, in _init_actions
    'fa.s    earch')
  File "/home/ede/tools/miniconda3/envs/opensesame3/lib/python3.7/site-packages/pyqode/core/icons.py", line 49, in icon
    ret_val = qta.icon(qta_name, **qta_options)
  File "/home/ede/tools/miniconda3/envs/opensesame3/lib/python3.7/site-packages/qtawesome/__init__.py", line 146, in icon
    return _instance().icon(*names, **kwargs)
  File "/home/ede/tools/miniconda3/envs/opensesame3/lib/python3.7/site-packages/qtawesome/iconic_font.py", line 305, in icon
    names[i]))
  File "/home/ede/tools/miniconda3/envs/opensesame3/lib/python3.7/site-packages/qtawesome/iconic_font.py", line 353, in _parse_options
    prefix, chars = self._get_prefix_chars(names)
  File "/home/ede/tools/miniconda3/envs/opensesame3/lib/python3.7/site-packages/qtawesome/iconic_font.py", line 384, in _get_prefix_chars
    raise Exception(error)
Exception: Invalid icon name "s    earch" in font "fa"
~~~

This happens on Ubuntu 18.04 with Opensesame 3.3.7 and 3.3.8. Earlier versions I have not checked, but also have not experienced issues with them.

Edit: Just tried 3.3.6, and it seems to work there.

**Comment by smathot** [comment]
This was actually a bug in `open-cogsci/pyqode.core`, but it was already fixed sometime ago. In general, if you update OpenSesame, I would also update these core dependencies (pyqode, rapunzel, datamatrix, etc.), because a lot of the functionality is actually in there.

**Comment by eort** [comment]
ah ok, I see. Maybe I have missed that, but would this would be a useful "note" or something like that in the manual?

**Comment by smathot** [comment]
Yes, that's a good point actually. I'll add a note, and ideally there would also be some stricter dependency check.
