### ISSUE TITLE
AttributeError: 'BackendManager' object has no attribute '_share_id'

### ISSUE THREAD

**Issue by behinger** [open-cogsci/OpenSesame#774]
Some students in the lab got this error in opensesame:

```
Traceback (most recent call last):
  File "XXX\Lib\site-packages\pyqode\core\managers\backend.py", line 284, in _send_heartbeat
    self.send_request(echo_worker, {'heartbeat': True})
  File "XXX\Lib\site-packages\pyqode\core\managers\backend.py", line 251, in send_request
    if not BackendManager.SHARE_COUNT.get(self._share_id, []):
AttributeError: 'BackendManager' object has no attribute '_share_id'
```
The error appeared at least once after running an experiment, also sometimes seemingly only in the main menu.  

After the error, apparently one needed to restart opensesame.

### Setup
We are making use of pygaze/GazePoint3 + some basic elements.
![grafik](https://user-images.githubusercontent.com/10183650/150194930-8aa43a92-a296-4248-b434-85e30a28360f.png)

### Related issues
I found #762 but it mainly talks about their other problem. @smathot  seems to know something about it though

We (@llips and others) will keep this issue updated - but maybe you have an idea already what it could be.

**Comment by smathot** [comment]
You  need to update `pyqode`, which consists of several packages named `pyqode.*`. You want to have the PyQode 3 fork, not the original PyQode. I'm 99% sure that's it, but could you confirm it so that I can close the issue?

- https://github.com/open-cogsci/pyqode.core
- https://osdoc.cogsci.nl/3.3/download/#anaconda-cross-platform

**Comment by behinger** [comment]
will test it as soon as I have access to the lab (likely next week). thanks for the quick response!
