### ISSUE TITLE
[BUG] changing color of rect in canvas fails in latest OS 4

### ISSUE THREAD

**Issue by eort** [open-cogsci/OpenSesame#811]
See [forum](https://forum.cogsci.nl/discussion/9147/changing-color-of-rect-canvas-does-no-longer-work-properly-in-version-4-0#latest): 

To reproduce:
```
my_canvas = Canvas()

my_canvas['rect'] = Rect(-100, -100, 200, 200)

my_canvas['rect'].color = "red" #runtime error that.color does not exist

my_canvas.show()
```
Produces:
```

['Traceback (most recent call last):', '  File "/home/ede/tools/miniconda3/envs/opensesame-py3/lib/python3.11/site-packages/libopensesame/inline_script.py", line 84, in run', '    self.workspace._exec(self.crun)', '  File "/home/ede/tools/miniconda3/envs/opensesame-py3/lib/python3.11/site-packages/libopensesame/base_python_workspace.py", line 99, in _exec', '    exec(bytecode, self._globals)  # __ignore_traceback__', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "<string>", line 10, in <module>', '  File "/home/ede/tools/miniconda3/envs/opensesame-py3/lib/python3.11/site-packages/openexp/_canvas/_element/element.py", line 232, in _setter', '    val = color(self.experiment, val)', '          ^^^^^', "NameError: name 'color' is not defined"]
['NoneType: None']

Error: PythonError
```

**Comment by smathot** [comment]
Already fixed in 8eba492c0aeeac8d62dda87a88f69d32797ecdcd. Make sure to test with the latest version!
